ignoredBuiltDependencies:
  - '@robinbobin/eslint-config'
  - '@robinbobin/eslint-config-react'

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@robinbobin/eslint-config-react-native'
  - '@robinbobin/prettier-config'
  - '@robinbobin/ts-config'
  - unrs-resolver
